name: Build and Publish project
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'
    tags-ignore:
      - 'v*'

jobs:
  build-forge:
    uses: ./.gitea/workflows/build-forge.yaml
